{% set name = "gh" %}
{% set version = "2.83.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cli/cli/archive/v{{ version }}.tar.gz
  sha256: c031ca887d3aaccb40402a224d901c366852f394f6b2b60d1158f20569e33c89

build:
  script_env:
    - GH_VERSION=v{{ version }}
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - {{ stdlib("c") }}
    - make  # [unix]

test:
  commands:
    - gh help
    - gh version

about:
  home: https://github.com/cli/cli
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Github CLI.
  doc_url: https://cli.github.com/
  dev_url: https://github.com/cli/cli

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - matthiasdiener
