{% set name = "gh" %}
{% set version = "2.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cli/cli/archive/v{{ version }}.tar.gz
  sha256: 8a5466f28ad2fb66b4a519167b45a0df66280245ac39c480fa6216ce7faa0b72

build:
  script_env:
    - GH_VERSION=v{{ version }}
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - make  # [unix]

test:
  commands:
    - gh help
    - gh version

about:
  home: https://github.com/cli/cli
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Github CLI.
  doc_url: https://cli.github.com/
  dev_url: https://github.com/cli/cli

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - matthiasdiener
