conda_forge_output_validation: true
provider:
  linux_aarch64: default
  osx_arm64: default
build_platform:
  linux_ppc64le: linux_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
bot:
  automerge: true
conda_build_tool: rattler-build
conda_install_tool: pixi
