bot:
  automerge: true
build_platform:
  linux_ppc64le: linux_64
  win_arm64: win_64
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  osx_arm64: default
test: native_and_emulated
